### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by teuben** [lmtoy/lmtoy_2021-S1-MX-3#1]
Here are things we need to do:

- [ ] finalize observations
- [x] bash or python for script generator  (-> python now)
- [ ] save final scripts
- [ ] args file or a master file
- [ ] who knows....

**Comment by teuben** [comment]
# Sources done so far:

- [ ] Arp143
- [ ] Arp91 (not in official list)
- [ ] NGC2540
- [ ] NGC5376
- [ ] NGC5473
- [ ] NGC5720
- [ ] NGC6786
